//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolRental_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public int ToolID { get; set; }
        public string ToolName { get; set; }
        public string Brand { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Rented { get; set; }
        public string PicFileName { get; set; }
    }
}
