//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolRental_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workspace
    {
        public int WorkspaceID { get; set; }
        public string WorkspaceName { get; set; }
    }
}
